---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.16.4

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[motd::default]
    attributes:
