---
driver:
  name: docker
  use_sudo: false
  socket: "<%= ENV['DOCKER_HOST']%>"

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.16.4

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[motd::default]
    attributes:
