---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  version: '12.2.1'

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[base::default]
    attributes:
